name: Update Shoots JSON

on:
  push:
    # re-run whenever the samples folder or the script or this workflow itself changes
    paths:
      - 'mateoSamples/**'
      - 'generateImageList.py'
      - '.github/workflows/updateImages.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate shoots JSON files
        run: python generateImageList.py

      - name: Commit & push JSON updates
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          # add both the master index and each per-shoot JSON
          git add shoots.json *.json
          git commit -m "chore: update shoots JSON" || echo "No changes to commit"
          git push origin main
