name: Update images.json

on:
  push:
    paths:
      - 'mateoSamples/**'
      - '.github/workflows/updateImages.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate images.json
        run: |
          python generateImageList.py

      - name: Commit and push if changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add images.json
          git commit -m "Update images.json" || echo "No changes to commit"
          git push
