name: Update images.json

on:
  push:
    paths:
      - 'mateoSamples/**'
      - 'generateImageList.py'
      - '.github/workflows/updateImages.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate images.json
        run: |
          python generateImageList.py

      - name: Commit and push if changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add images.json
          git commit -m "Update images.json" || echo "No changes to commit"
          git push origin main
